version: '3.8'

services:
  db:
    image: postgres:16-alpine3.20 # A imagem que o Docker vai baixar
    container_name: forum_dev
    restart: always
    environment:
      # SUAS CREDENCIAIS DO POSTGRESQL:
      POSTGRES_USER: forum_postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forum_db
    ports:
      - '5433:5432' # A porta padrão do PostgreSQL, acessível na sua máquina
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: